[package]
name = "knave-wayland"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Knave-owned Wayland layer-shell runtime"

[dependencies]
knave-renderer.workspace = true
knave-desktop-api.workspace = true
knave-ui.workspace = true
base64.workspace = true
png.workspace = true
pollster.workspace = true
smithay-client-toolkit.workspace = true
thiserror.workspace = true
wayland-client.workspace = true
wgpu.workspace = true
rustix = { version = "1", features = ["fs"] }
wayland-protocols = { version = "0.32", features = ["client", "unstable"] }
